---
- hosts: localhost
  user: root

  vars_files:
    - "{{ lookup('env', 'UNIVERSAL_VARS_FILE') }}"

  pre_tasks:
    - include_vars: secrets.yml
      ignore_errors: yes
      tags:
        - always

  roles:
    - facts
    - nodejs
